import { beforeAll, describe, expect, it } from 'vitest';
import bcrypt from 'bcryptjs';
import { randomUUID } from 'node:crypto';
import type { Actor } from '../src/lib/auth';

let db: typeof import('../src/lib/db')['db'];
let b: typeof import('../src/lib/business');
let boss: Actor, staff: Actor, customer: any, owner: any, location: any;
const code = () => `T-${randomUUID().slice(0,8)}`;
beforeAll(async () => {
  process.loadEnvFile('.env');
  if (!process.env.DATABASE_URL?.includes('/feicui_test?')) throw new Error('测试必须使用 feicui_test 独立数据库');
  db=(await import('../src/lib/db')).db;
  b=await import('../src/lib/business');
  const merchant=await db.merchant.create({data:{name:'自动验收-'+code()}});
  const pass=await bcrypt.hash('test-only',4);
  const user=await db.user.create({data:{merchantId:merchant.id,login:code(),name:'老板',role:'OWNER',passwordHash:pass}});
  const user2=await db.user.create({data:{merchantId:merchant.id,login:code(),name:'员工',role:'STAFF',passwordHash:pass,permissions:{goods:true,loans:true,partnersRead:true}}});
  boss={id:user.id,merchantId:merchant.id,name:user.name,role:user.role,permissions:user.permissions,active:true};
  staff={id:user2.id,merchantId:merchant.id,name:user2.name,role:user2.role,permissions:user2.permissions,active:true};
  customer=await db.partner.create({data:{merchantId:merchant.id,name:'客户A',roles:['CUSTOMER']}});
  staff={...staff,permissions:{goods:true,loans:true,partnersRead:true,customerIds:[customer.id]}};
  await db.user.update({where:{id:user2.id},data:{permissions:{goods:true,loans:true,partnersRead:true,customerIds:[customer.id]}}});
  owner=await db.partner.create({data:{merchantId:merchant.id,name:'上游甲',roles:['OWNER'],settlementType:'RATE',settlementRateBp:8000}});
  location=await db.location.create({data:{merchantId:merchant.id,name:'摊位'}});
},120000);

describe('摊主主流程',()=>{
  it('扫描货号入库只生成一件货及一条入库流水，重复货号回滚',async()=>{
    const scannedCode=code();
    const good=await b.createGood(boss,{code:scannedCode,name:'扫码手镯',category:'手镯',ownershipKind:'OWN',locationId:location.id});
    expect(good.code).toBe(scannedCode);
    expect(good.occupancy).toBe('FREE');
    expect(await db.inventoryEvent.count({where:{merchantId:boss.merchantId,goodId:good.id,action:'OWN_RECEIPT'}})).toBe(1);
    await expect(b.createGood(boss,{code:scannedCode,name:'重复货',category:'手镯',locationId:location.id})).rejects.toThrow();
    expect(await db.good.count({where:{merchantId:boss.merchantId,code:scannedCode}})).toBe(1);
    expect(await db.inventoryEvent.count({where:{merchantId:boss.merchantId,goodId:good.id}})).toBe(1);
  });
  it('50件货一物一码，10件拿货后4件归还、3件成交、3件仍在外借',async()=>{
    const goods: Awaited<ReturnType<typeof b.createGood>>[]=[];
    for(let i=0;i<50;i++)goods.push(await b.createGood(boss,{name:'演示货'+i,category:'手镯',ownershipKind:i>=25?'CONSIGN':'OWN',ownerPartnerId:i>=25?owner.id:undefined,locationId:location.id,asking:'1000.00',cost:i>=25?undefined:'500.00'}));
    expect(new Set(goods.map(g=>g.code)).size).toBe(50);
    const loan=await b.createLoan(boss,{partnerId:customer.id,receiverName:'客户A',goodIds:goods.slice(0,10).map(g=>g.id)});
    for(let i=0;i<4;i++){const item=loan.items.find(x=>x.goodId===goods[i].id)!;await b.returnLoanItem(boss,item.id,{condition:i===0?'DAMAGED':'NORMAL',locationId:location.id,note:i===0?'表面磕碰':'正常'});}
    const sale=await b.createSale(boss,{customerId:customer.id,items:goods.slice(4,7).map(g=>({goodId:g.id,price:'900.00'})),discount:'0',delivered:true});
    expect(sale.items).toHaveLength(3);
    const out=await db.loanItem.count({where:{merchantId:boss.merchantId,status:'OUT'}});
    expect(out).toBe(3);
    const damaged=await db.good.findUniqueOrThrow({where:{id:goods[0].id}});
    expect(damaged.quality).toBe('HOLD');
    expect(damaged.occupancy).toBe('FREE');
    expect(await db.moneyEntry.count({where:{merchantId:boss.merchantId,kind:'CUSTOMER_REFUND'}})).toBe(0);
    const stock=await b.createStocktake(boss,location.id);
    expect(stock.items.some(i=>i.goodId===goods[9].id)).toBe(false);
  },120000);
  it('并发员工不能重复借同一件货，也不能卖外借给其他客户的货',async()=>{
    const g=await b.createGood(boss,{name:'并发货',category:'挂件',locationId:location.id});
    const attempts=await Promise.allSettled([b.createLoan(boss,{partnerId:customer.id,receiverName:'甲',goodIds:[g.id]}),b.createLoan(staff,{partnerId:customer.id,receiverName:'甲',goodIds:[g.id]})]);
    expect(attempts.filter(x=>x.status==='fulfilled')).toHaveLength(1);
    expect(await db.loanItem.count({where:{goodId:g.id,status:'OUT'}})).toBe(1);
    await expect(b.createSale(boss,{customerId:owner.id,items:[{goodId:g.id,price:'100.00'}]})).rejects.toThrow();
    const saleGood=await b.createGood(boss,{name:'并发成交货',category:'挂件',locationId:location.id});
    const sales=await Promise.allSettled([b.createSale(boss,{customerId:customer.id,items:[{goodId:saleGood.id,price:'100.00'}]}),b.createSale(boss,{customerId:customer.id,items:[{goodId:saleGood.id,price:'100.00'}]})]);
    expect(sales.filter(x=>x.status==='fulfilled')).toHaveLength(1);
    expect(await db.saleItem.count({where:{goodId:saleGood.id,status:'ACTIVE'}})).toBe(1);
  });
  it('客户分次付款、多单核销，寄售应付独立且付清客户款才可付款',async()=>{
    const g1=await b.createGood(boss,{name:'寄售一',category:'戒面',ownershipKind:'CONSIGN',ownerPartnerId:owner.id,locationId:location.id,settlementType:'RATE',settlementRateBp:8000});
    const g2=await b.createGood(boss,{name:'寄售二',category:'戒面',ownershipKind:'CONSIGN',ownerPartnerId:owner.id,locationId:location.id,settlementType:'RATE',settlementRateBp:8000});
    const s1=await b.createSale(boss,{customerId:customer.id,items:[{goodId:g1.id,price:'100.00'}],delivered:true});
    const s2=await b.createSale(boss,{customerId:customer.id,items:[{goodId:g2.id,price:'200.00'}],delivered:true});
    expect(await db.payable.count({where:{merchantId:boss.merchantId,saleItemId:{in:[s1.items[0].id,s2.items[0].id]}}})).toBe(2);
    const p1=await db.payable.findUniqueOrThrow({where:{saleItemId:s1.items[0].id}});
    expect(p1.amountCents).toBe(8000n);
    await expect(b.createPayment(boss,{ownerId:owner.id,amount:'80.00',allocations:[{payableId:p1.id,amount:'80.00'}]})).rejects.toThrow();
    await b.createReceipt(boss,{partnerId:customer.id,kind:'SALES',amount:'100.00',method:'现金',allocations:[{saleItemId:s1.items[0].id,amount:'50.00'},{saleItemId:s2.items[0].id,amount:'50.00'}]});
    const halfway=await db.saleItem.findMany({where:{id:{in:[s1.items[0].id,s2.items[0].id]}}});
    expect(halfway.reduce((n,x)=>n+x.netCents-x.paidCents,0n)).toBe(20000n);
    await b.createReceipt(boss,{partnerId:customer.id,kind:'SALES',amount:'200.00',method:'转账',allocations:[{saleItemId:s1.items[0].id,amount:'50.00'},{saleItemId:s2.items[0].id,amount:'150.00'}]});
    const paid=await db.saleItem.findUniqueOrThrow({where:{id:s1.items[0].id}});expect(paid.paidCents).toBe(10000n);
    expect((await db.saleItem.findUniqueOrThrow({where:{id:s2.items[0].id}})).paidCents).toBe(20000n);
    await b.createPayment(boss,{ownerId:owner.id,amount:'80.00',allocations:[{payableId:p1.id,amount:'80.00'}]});
    await b.returnSaleItem(boss,s1.items[0].id,{physical:true,amount:'100.00',refund:'100.00',reason:'客户退货',locationId:location.id});
    const after=await db.payable.findUniqueOrThrow({where:{id:p1.id}});
    expect(after.paidCents).toBe(8000n);expect(after.adjustedCents).toBe(-8000n);
    expect(await db.moneyEntry.count({where:{merchantId:boss.merchantId,kind:'SUPPLIER_CREDIT_PENDING',relatedId:p1.id}})).toBe(1);
  },120000);
  it('押金部分抵款部分退还，余额不能透支',async()=>{
    const g=await b.createGood(boss,{name:'押金货',category:'挂件',locationId:location.id});
    const s=await b.createSale(boss,{customerId:customer.id,items:[{goodId:g.id,price:'100.00'}]});
    const r=await b.createReceipt(boss,{partnerId:customer.id,kind:'DEPOSIT',amount:'80.00',method:'现金'});
    await b.applyDeposit(boss,r.id,s.items[0].id,'30.00');
    await b.refundDeposit(boss,r.id,'50.00','客户结清押金');
    const current=await db.receipt.findUniqueOrThrow({where:{id:r.id}});expect(current.allocatedCents).toBe(8000n);
    expect((await db.saleItem.findUniqueOrThrow({where:{id:s.items[0].id}})).paidCents).toBe(3000n);
    await expect(b.refundDeposit(boss,r.id,'1.00','超额')).rejects.toThrow();
  });
  it('分次改价后应付归零，已付上游款只生成新增的待处理差额',async()=>{
    const g=await b.createGood(boss,{name:'分次改价货',category:'戒面',ownershipKind:'CONSIGN',ownerPartnerId:owner.id,locationId:location.id,settlementType:'RATE',settlementRateBp:5000});
    const s=await b.createSale(boss,{customerId:customer.id,items:[{goodId:g.id,price:'0.03'}],delivered:true});
    const si=s.items[0];
    const payable=await db.payable.findUniqueOrThrow({where:{saleItemId:si.id}});
    expect(payable.amountCents).toBe(2n);
    await b.createReceipt(boss,{partnerId:customer.id,kind:'SALES',amount:'0.03',method:'现金',allocations:[{saleItemId:si.id,amount:'0.03'}]});
    await b.createPayment(boss,{ownerId:owner.id,amount:'0.02',allocations:[{payableId:payable.id,amount:'0.02'}]});
    await b.returnSaleItem(boss,si.id,{physical:false,amount:'0.01',reason:'首次改价'});
    await b.returnSaleItem(boss,si.id,{physical:false,amount:'0.02',reason:'再次改价'});
    const finalPayable=await db.payable.findUniqueOrThrow({where:{id:payable.id}});
    expect(finalPayable.amountCents+finalPayable.adjustedCents).toBe(0n);
    const credits=await db.moneyEntry.findMany({where:{merchantId:boss.merchantId,kind:'SUPPLIER_CREDIT_PENDING',relatedId:payable.id}});
    expect(credits.reduce((n,x)=>n+x.amountCents,0n)).toBe(2n);
  });
  it('合作方默认分成改版不追改旧货约定，成交快照按逐件优惠净额计算',async()=>{
    const supplier=await b.createPartner(boss,{name:'规则版本货主',roles:['OWNER'],settlementType:'RATE',settlementRateBp:8000});
    const old=await b.createGood(boss,{name:'旧规则货',category:'戒面',ownershipKind:'CONSIGN',ownerPartnerId:supplier.id,locationId:location.id});
    await b.updatePartner(boss,supplier.id,{settlementType:'RATE',settlementRateBp:5000});
    const fresh=await b.createGood(boss,{name:'新规则货',category:'戒面',ownershipKind:'CONSIGN',ownerPartnerId:supplier.id,locationId:location.id});
    const sale=await b.createSale(boss,{customerId:customer.id,items:[{goodId:old.id,price:'100.00'},{goodId:fresh.id,price:'200.00'}],discount:'30.00'});
    const payables=await db.payable.findMany({where:{saleItemId:{in:sale.items.map(x=>x.id)}}});
    const oldPay=payables.find(x=>sale.items.find(i=>i.goodId===old.id)?.id===x.saleItemId)!;
    const newPay=payables.find(x=>sale.items.find(i=>i.goodId===fresh.id)?.id===x.saleItemId)!;
    expect(oldPay.amountCents).toBe(7200n);
    expect(newPay.amountCents).toBe(9000n);
    expect((oldPay.ruleSnapshot as any).ruleVersion).toBe(1);
    expect((newPay.ruleSnapshot as any).ruleVersion).toBe(2);
  });
  it('权限与商家隔离由服务端检查',async()=>{
    await expect(b.createPayment(staff,{ownerId:owner.id,amount:'1.00',allocations:[]})).rejects.toMatchObject({status:403});
    const hidden=await db.partner.create({data:{merchantId:boss.merchantId,name:'未分配客户',roles:['CUSTOMER']}});
    await expect(b.createLoan(staff,{partnerId:hidden.id,receiverName:'未授权',goodIds:['none']})).rejects.toMatchObject({status:404});
    const hiddenGood=await b.createGood(boss,{name:'未分配客户拿货',category:'挂件',locationId:location.id});
    const hiddenLoan=await b.createLoan(boss,{partnerId:hidden.id,receiverName:'未分配',goodIds:[hiddenGood.id]});
    await expect(b.returnLoanItem(staff,hiddenLoan.items[0].id,{condition:'NORMAL'})).rejects.toMatchObject({status:404});
    const scoped={...staff,permissions:{...(staff.permissions as object),receipts:true}};
    await expect(b.createReceipt(scoped,{partnerId:hidden.id,kind:'SALES',amount:'1.00',method:'现金'})).rejects.toMatchObject({status:404});
    const other=await db.merchant.create({data:{name:'其他商家'}});
    const p=await db.partner.create({data:{merchantId:other.id,name:'其他客户'}});
    await expect(b.createLoan(boss,{partnerId:p.id,receiverName:'外部',goodIds:['none']})).rejects.toMatchObject({status:404});
  });
  it('期初应收应付独立登记，并能由真实收付款核销',async()=>{
    const ar=await b.openingBalance(boss,{partnerId:customer.id,kind:'AR',amount:'120.00',note:'期初确认'});
    const ap=await b.openingBalance(boss,{partnerId:owner.id,kind:'AP',amount:'90.00',note:'期初确认'});
    const r=await b.createReceipt(boss,{partnerId:customer.id,kind:'SALES',amount:'120.00',method:'现金'});
    await b.allocateOpeningReceipt(boss,r.id,ar.id,'120.00');
    await b.createPayment(boss,{ownerId:owner.id,amount:'90.00',method:'转账',allocations:[{openingEntryId:ap.id,amount:'90.00'}]});
    expect((await db.moneyEntry.findUniqueOrThrow({where:{id:ar.id}})).appliedCents).toBe(12000n);
    expect((await db.moneyEntry.findUniqueOrThrow({where:{id:ap.id}})).appliedCents).toBe(9000n);
  });
  it('一件无效货使整张多件销售回滚，不留单据和占用',async()=>{
    const valid=await b.createGood(boss,{name:'有效货',category:'挂件',locationId:location.id});
    const invalid=await b.createGood(boss,{name:'无效货',category:'挂件',locationId:location.id});
    await b.reserveGood(boss,invalid.id,true);
    await b.createSale(boss,{customerId:customer.id,items:[{goodId:invalid.id,price:'100.00'}]});
    const before=await db.sale.count({where:{merchantId:boss.merchantId}});
    await expect(b.createSale(boss,{customerId:customer.id,items:[{goodId:valid.id,price:'100.00'},{goodId:invalid.id,price:'100.00'}]})).rejects.toThrow();
    expect(await db.sale.count({where:{merchantId:boss.merchantId}})).toBe(before);
    expect((await db.good.findUniqueOrThrow({where:{id:valid.id}})).occupancy).toBe('FREE');
  });
  it('盘点期间流转的货品重新核实后可以结束，不误记移出货为盘亏',async()=>{
    const shelf=await db.location.create({data:{merchantId:boss.merchantId,name:'复核货位-'+code()}});
    const elsewhere=await db.location.create({data:{merchantId:boss.merchantId,name:'移出货位-'+code()}});
    const reserved=await b.createGood(boss,{name:'盘点期间预留',category:'挂件',locationId:shelf.id});
    const moved=await b.createGood(boss,{name:'盘点期间移位',category:'挂件',locationId:shelf.id});
    const take=await b.createStocktake(boss,shelf.id);
    await b.reserveGood(boss,reserved.id,true);
    await b.moveLocation(boss,moved.id,elsewhere.id,'正常位置调整');
    await expect(b.closeStocktake(boss,take.id,'')).rejects.toMatchObject({status:400});
    await expect(b.closeStocktake(boss,take.id,'复核结束')).rejects.toMatchObject({status:409});
    expect(await b.markStocktake(boss,take.id,reserved.code)).toMatchObject({kind:'RECHECK'});
    expect(await b.markStocktake(boss,take.id,moved.code)).toMatchObject({kind:'MOVED_OUT'});
    expect(await b.closeStocktake(boss,take.id,'已核实预留与移位')).toEqual({missing:0});
    expect((await db.good.findUniqueOrThrow({where:{id:moved.id}})).quality).toBe('NORMAL');
  });
  it('盘点多货、错位和未登记货号留痕，老板逐项处置后才能结束',async()=>{
    const shelf=await db.location.create({data:{merchantId:boss.merchantId,name:'差异货位-'+code()}});
    const elsewhere=await db.location.create({data:{merchantId:boss.merchantId,name:'其他货位-'+code()}});
    const misplaced=await b.createGood(boss,{name:'错位货',category:'挂件',locationId:elsewhere.id});
    const take=await b.createStocktake(boss,shelf.id);
    const added=await b.createGood(boss,{name:'快照后入库货',category:'挂件',locationId:shelf.id});
    expect(await b.markStocktake(boss,take.id,misplaced.code)).toMatchObject({kind:'WRONG_LOCATION'});
    expect(await b.markStocktake(boss,take.id,added.code)).toMatchObject({kind:'EXTRA'});
    expect(await b.markStocktake(boss,take.id,'NO-SUCH-GOOD')).toMatchObject({kind:'UNREGISTERED'});
    const findings=await db.stocktakeFinding.findMany({where:{stocktakeId:take.id}});
    expect(findings).toHaveLength(3);
    await expect(b.closeStocktake(boss,take.id,'发现差异待核实')).rejects.toMatchObject({status:409});
    await expect(b.resolveStocktakeFinding(staff,findings[0].id,'IGNORE','无权复核')).rejects.toMatchObject({status:403});
    const unknown=findings.find(f=>f.kind==='UNREGISTERED')!;
    const wrong=findings.find(f=>f.kind==='WRONG_LOCATION')!;
    const extra=findings.find(f=>f.kind==='EXTRA')!;
    await expect(b.resolveStocktakeFinding(boss,unknown.id,'MOVE_HERE','账外货')).rejects.toMatchObject({status:409});
    await b.resolveStocktakeFinding(boss,unknown.id,'IGNORE','已核实为外来货，另行登记');
    await b.resolveStocktakeFinding(boss,wrong.id,'MOVE_HERE','已确认实物在此货位');
    await b.resolveStocktakeFinding(boss,extra.id,'MOVE_HERE','快照后新入库且在本货位');
    await expect(b.resolveStocktakeFinding(boss,wrong.id,'MOVE_HERE','重复处置')).rejects.toMatchObject({status:404});
    expect(await b.closeStocktake(boss,take.id,'已逐项复核差异')).toEqual({missing:0});
    expect((await db.good.findUniqueOrThrow({where:{id:misplaced.id}})).locationId).toBe(shelf.id);
    expect(await db.stocktakeItem.count({where:{stocktakeId:take.id,goodId:misplaced.id,seen:true}})).toBe(1);
    expect(await db.stocktakeItem.count({where:{stocktakeId:take.id,goodId:added.id,seen:true}})).toBe(1);
    expect(await db.stocktakeFinding.count({where:{stocktakeId:take.id,status:'RESOLVED'}})).toBe(3);
    expect(await db.inventoryEvent.count({where:{goodId:misplaced.id,action:'STOCKTAKE_EXTRA_MOVE'}})).toBe(1);
  });
  it('异常货由老板留痕复核，恢复或报损均不自动生成扣款',async()=>{
    const good=await b.createGood(boss,{name:'修复中的货',category:'手镯',locationId:location.id});
    const loan=await b.createLoan(boss,{partnerId:customer.id,receiverName:'客户A',goodIds:[good.id]});
    await b.returnLoanItem(boss,loan.items[0].id,{condition:'DAMAGED',locationId:location.id,note:'表面磕碰待检查'});
    const damage=await db.damage.findFirstOrThrow({where:{merchantId:boss.merchantId,goodId:good.id,resolvedAt:null}});
    const image=await db.goodImage.create({data:{merchantId:boss.merchantId,goodId:good.id,fileName:'test-evidence.jpg',mimeType:'image/jpeg'}});
    const moneyBefore=await db.moneyEntry.count({where:{merchantId:boss.merchantId}});
    await expect(b.reviewDamage(staff,damage.id,{disposition:'RESTORE',responsibility:'CUSTOMER',reason:'员工擅自放行'})).rejects.toMatchObject({status:403});
    expect(await b.reviewDamage(boss,damage.id,{disposition:'KEEP_HOLD',responsibility:'UNCONFIRMED',reason:'继续等待检查',imageId:image.id})).toMatchObject({status:'OPEN',quality:'HOLD'});
    expect((await db.damage.findUniqueOrThrow({where:{id:damage.id}})).photoFile).toBe(image.id);
    expect(await b.reviewDamage(boss,damage.id,{disposition:'RESTORE',responsibility:'MERCHANT',reason:'已检查修复且确认正常'})).toMatchObject({status:'RESOLVED',quality:'NORMAL'});
    expect((await db.good.findUniqueOrThrow({where:{id:good.id}})).quality).toBe('NORMAL');
    await expect(b.reviewDamage(boss,damage.id,{disposition:'RESTORE',responsibility:'MERCHANT',reason:'重复结案'})).rejects.toMatchObject({status:404});
    const written=await b.createGood(boss,{name:'报损货',category:'手镯',locationId:location.id});
    const loan2=await b.createLoan(boss,{partnerId:customer.id,receiverName:'客户A',goodIds:[written.id]});
    await b.returnLoanItem(boss,loan2.items[0].id,{condition:'DAMAGED',locationId:location.id,note:'明显破损'});
    const damage2=await db.damage.findFirstOrThrow({where:{merchantId:boss.merchantId,goodId:written.id,resolvedAt:null}});
    await b.reviewDamage(boss,damage2.id,{disposition:'WRITE_OFF',responsibility:'CUSTOMER',reason:'确认破损，暂不确定赔付'});
    expect((await db.good.findUniqueOrThrow({where:{id:written.id}})).quality).toBe('DAMAGED');
    expect(await db.moneyEntry.count({where:{merchantId:boss.merchantId}})).toBe(moneyBefore);
    const shelf=await db.location.create({data:{merchantId:boss.merchantId,name:'盘点异常货位-'+code()}});
    const missingGood=await b.createGood(boss,{name:'盘点未见货',category:'挂件',locationId:shelf.id});
    const take=await b.createStocktake(boss,shelf.id);
    expect(await b.closeStocktake(boss,take.id,'复核后仍未见实物')).toEqual({missing:1});
    expect((await db.good.findUniqueOrThrow({where:{id:missingGood.id}})).quality).toBe('HOLD');
    expect(await db.damage.count({where:{merchantId:boss.merchantId,goodId:missingGood.id,resolvedAt:null}})).toBe(1);
  });
});
