'use client';
import { useCallback, useEffect, useState } from 'react';
import CameraScanner from './CameraScanner';
import StocktakeReview from './StocktakeReview';
import DamageReview from './DamageReview';

type Any = Record<string, any>;
const nav = [{id:'home',label:'首页',icon:'⌂'},{id:'goods',label:'货品',icon:'◇'},{id:'loans',label:'拿货单',icon:'⇄'},{id:'accounts',label:'往来账',icon:'¥'},{id:'mine',label:'我的',icon:'☰'}];
async function api(path: string, method = 'GET', body?: any) {
  const r = await fetch(`/api/v1/${path}`, { method, headers: body ? { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() } : undefined, body: body ? JSON.stringify(body) : undefined });
  const result = await r.json(); if (!r.ok) throw new Error(result.error || '操作失败'); return result;
}
const price = (v: any) => v==null?'—':`¥${Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date = (v: any) => v ? new Date(v).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'}) : '未设置';
function Field({label,name,type='text',required=false,children,defaultValue}:any){return <label>{label}{children || <input name={name} type={type} required={required} defaultValue={defaultValue}/>}</label>}
function Select({label,name,options,required=true}:any){return <Field label={label}><select name={name} required={required}><option value="">请选择</option>{options.map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>}
function Form({title,children,onSubmit,submit='保存'}:any){return <div className="panel"><h2>{title}</h2><form className="form" onSubmit={onSubmit}>{children}<button className="primary span2" type="submit">{submit}</button></form></div>}
export default function Page(){
  const [me,setMe]=useState<Any|null|undefined>(undefined),[tab,setTab]=useState('home'),[data,setData]=useState<Any>({}),[message,setMessage]=useState(''),[error,setError]=useState(''),[form,setForm]=useState(''),[selected,setSelected]=useState<string[]>([]),[filter,setFilter]=useState(''),[pickerSearch,setPickerSearch]=useState(''),[stocktakeCode,setStocktakeCode]=useState(''),[shareUrl,setShareUrl]=useState(''),[lastCreated,setLastCreated]=useState<Any|null>(null);
  const load=useCallback(async()=>{try{const user=await api('me');setMe(user);const names=['dashboard','partners','locations','goods','loans','sales','receipts','payables','stocktakes','damages','users','shares','money-entries'];const values=await Promise.all(names.map(n=>api(n).catch(()=>[])));setData(Object.fromEntries(names.map((n,i)=>[n,values[i]])));}catch{setMe(null)}},[]);
  useEffect(()=>{load()},[load]);
  async function act(path:string,body:any,done='已保存'){setError('');setMessage('');try{const result=await api(path,'POST',body);if(path==='goods'){setLastCreated(result);setMessage(`已入库 ${result.code}，可打印标签`)}else setMessage(done);setForm('');setSelected([]);await load()}catch(e:any){setError(e.message)}}
  async function scanStocktake(id:string,code:string){setError('');setMessage('');try{const result=await api(`stocktakes/${id}/scan`,'POST',{code});setStocktakeCode('');setMessage(({SEEN:'已核对',RECHECK:'流转后已重新核对',MOVED_OUT:'已确认移出本位置',EXTRA:'快照外多货，待复核',WRONG_LOCATION:'错位货，待复核',UNREGISTERED:'未登记货号，待复核'} as Record<string,string>)[result.kind]||'已记录差异');await load()}catch(e:any){setError(e.message)}}
  async function resolveFinding(id:string,disposition:string,reason:string){setError('');setMessage('');try{await api(`stocktake-findings/${id}/resolve`,'POST',{disposition,reason});setMessage('差异已复核');await load()}catch(e:any){setError(e.message)}}
  function submit(path:string,build:(f:FormData)=>any,done?:string){return (e:any)=>{e.preventDefault();const f=new FormData(e.currentTarget);act(path,build(f),done)}}
  const f=(x:FormData,k:string)=>String(x.get(k)||'');
  const partners=(data.partners||[]) as Any[], goods=(data.goods||[]) as Any[], locations=(data.locations||[]) as Any[], loans=(data.loans||[]) as Any[], sales=(data.sales||[]) as Any[], receipts=(data.receipts||[]) as Any[], payables=(data.payables||[]) as Any[], takes=(data.stocktakes||[]) as Any[], damages=(data.damages||[]) as Any[], users=(data.users||[]) as Any[], shares=(data.shares||[]) as Any[], entries=(data['money-entries']||[]) as Any[];
  const goodOptions=goods.filter(g=>g.occupancy==='FREE'&&g.holderKind==='MERCHANT'&&g.quality==='NORMAL'&&!g.returnedUpstreamAt);
  const loanOptions=goods.filter(g=>g.occupancy==='LOAN');
  const selectedGoods=goods.filter(g=>selected.includes(g.id));
  function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(v=>v!==id):[...s,id])}
  if(me===undefined)return <div className="login"><div className="loginbox">正在读取账本…</div></div>;
  if(me===null)return <div className="login"><div className="loginbox"><h1>翠账</h1><p>翡翠摊主管货与对账</p><form onSubmit={async e=>{e.preventDefault();const x=new FormData(e.currentTarget);try{await api('login','POST',{login:f(x,'login'),password:f(x,'password')});await load()}catch(err:any){setError(err.message)}}}><label>账号<input name="login" autoComplete="username" required/></label><label>密码<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<div className="error">{error}</div>}<button className="primary">登录</button></form></div></div>;
  const choose=(id:string)=>{setTab(id);setForm('');setError('');setMessage('');setSelected([])};
  const open=(id:string)=>{setForm(id);setError('');setMessage('');setPickerSearch('');window.scrollTo({top:0,behavior:'smooth'})};
  return <div className="shell"><aside className="sidebar"><div className="brand">翠账<small>货在哪里，账就在哪里</small></div><div className="nav">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>choose(n.id)}>{n.icon}　{n.label}</button>)}</div><div className="sidefoot">{me.name} · {me.role==='OWNER'?'老板':'员工'}</div></aside><main className="main"><div className="top"><div><h1>{nav.find(n=>n.id===tab)?.label}</h1><p>{tab==='home'?'今天的货和账，一眼看清':tab==='goods'?'一物一码，随时查货':tab==='loans'?'谁拿走了，还剩几件没还':tab==='accounts'?'客户应收和上游应付各算各的':'基础资料和管理'}</p></div><button className="softbutton" onClick={load}>刷新</button></div>{message&&<div className="success">{message}</div>}{error&&<div className="error">{error}</div>}{shareUrl&&<div className="success">分享链接：<a href={shareUrl} target="_blank" rel="noreferrer">{shareUrl}</a>　<button className="softbutton small" onClick={()=>navigator.clipboard.writeText(shareUrl)}>复制</button></div>}
  {tab==='home'&&<><div className="grid">{[['在手可售',data.dashboard?.inHand,'件'],['外借未还',data.dashboard?.onLoan,'件'],['客户未付',price(data.dashboard?.customerUnpaid),''],['上游未付',price(data.dashboard?.supplierUnpaid),''],['今日成交',price(data.dashboard?.todaySales),''],['本月成交',price(data.dashboard?.monthSales),''],['本月实收',price(data.dashboard?.received),''],['本月毛利估算',data.dashboard?.profitIncomplete?'资料不足':price(data.dashboard?.profit),''],['待处理货损',data.dashboard?.damages,'件']].map(([l,v,u],i)=><div className={`card metric ${i===2||i===3?'alert':''}`} key={String(l)}><label>{l}</label><strong>{v}{u}</strong></div>)}</div><div className="actions"><button className="primary" onClick={()=>{choose('goods');open('good')}}>＋ 拍照录货</button><button className="primary" onClick={()=>{choose('loans');open('loan')}}>＋ 客户拿货</button><button className="softbutton" onClick={()=>choose('loans')}>归还验货</button><button className="softbutton" onClick={()=>{choose('accounts');open('sale')}}>确认成交</button><button className="softbutton" onClick={()=>{choose('accounts');open('receipt')}}>登记收款</button></div><div className="section"><h2>需要留意</h2><div className="card">{data.dashboard?.overdue||0} 件外借已过约定归还时间；{data.dashboard?.stale||0} 件货超过90天未成交；{data.dashboard?.damages||0} 件货损待处理。外借货不会算作摊位缺货。</div></div></>}
  {tab==='goods'&&lastCreated&&<div className="success">新货号 {lastCreated.code}　<a className="softbutton small" href={`/labels/${lastCreated.id}`}>打印刚入库的标签</a></div>}
  {tab==='goods'&&<><div className="actions"><button className="primary" onClick={()=>open('good')}>＋ 录入货品</button><button className="softbutton" onClick={()=>open('move')}>调整位置</button><button className="softbutton" onClick={()=>open('stocktake')}>发起盘点</button><button className="softbutton" onClick={()=>open('import')}>表格导入</button></div>{form==='good'&&<Form title="快速录货" onSubmit={submit('goods',x=>({code:f(x,'code')||undefined,name:f(x,'name'),category:f(x,'category'),ownershipKind:f(x,'ownershipKind'),ownerPartnerId:f(x,'ownerPartnerId')||undefined,sourcePartnerId:f(x,'sourcePartnerId')||undefined,locationId:f(x,'locationId')||undefined,asking:f(x,'asking')||undefined,cost:f(x,'cost')||undefined,settlementType:f(x,'settlementType')||undefined,settlementFixed:f(x,'settlementFixed')||undefined,settlementRateBp:f(x,'settlementRateBp')||undefined}))}><Field label="货号（留空由系统自动生成）" name="code"/><Field label="货品名称" name="name" required/><Field label="品类" name="category" required/><Field label="货权类型"><select name="ownershipKind"><option value="OWN">自有货</option><option value="CONSIGN">寄售货</option></select></Field><Select label="上游货主（寄售必选）" name="ownerPartnerId" options={partners} required={false}/><Select label="采购来源" name="sourcePartnerId" options={partners} required={false}/><Select label="存放位置" name="locationId" options={locations} required={false}/><Field label="对外报价（元）" name="asking"/>{(me.role==='OWNER'||me.permissions?.cost)&&<><Field label="采购成本（元）" name="cost"/><Field label="结算方式"><select name="settlementType"><option value="">沿用货主规则</option><option value="FIXED">固定价</option><option value="RATE">比例分成</option></select></Field><Field label="固定结算价（元）" name="settlementFixed"/><Field label="分成万分比（例如8000＝80%）" name="settlementRateBp"/></>}</Form>}
  {form==='move'&&<Form title="调整存放位置" onSubmit={submit('goods/'+selected[0]+'/move',x=>({locationId:f(x,'locationId'),reason:f(x,'reason')}))}><Select label="新位置" name="locationId" options={locations}/><Field label="原因" name="reason"/></Form>}
  {form==='stocktake'&&<Form title="发起盘点" onSubmit={submit('stocktakes',x=>({locationId:f(x,'locationId')}))}><Select label="盘点位置" name="locationId" options={locations}/></Form>}
  {form==='import'&&<ImportBox onDone={load}/>}
  <div className="scan-search"><input className="search" placeholder="输入货号或关键词查货" value={filter} onChange={e=>setFilter(e.target.value)}/><CameraScanner onScan={setFilter}/></div><div className="section list">{goods.filter(g=>!filter||`${g.code} ${g.name} ${g.category}`.includes(filter)).map(g=><div className="item" key={g.id}>{g.images?.[0]?<img className="thumb" src={`/api/media/${g.images[0].id}`} alt={g.name}/>:<div className="placeholder">◇</div>}<div className="body"><h3>{g.code} · {g.name}</h3><p>{g.category} · {g.ownershipKind==='CONSIGN'?'寄售':'自有'} · {g.holderKind==='PARTNER'?'客户持有':'摊位/库房'} · {g.quality==='NORMAL'?'品质正常':'待处理'}</p><div className="row"><span className={`badge ${g.occupancy==='LOAN'?'warn':g.occupancy==='SOLD'?'red':''}`}>{({FREE:'可用',LOAN:'外借',RESERVED:'预留',SOLD:'已成交'} as any)[g.occupancy]}</span><span className="muted">报价 {price(g.askingCents)}</span></div></div><div className="row"><button className="softbutton small" onClick={()=>open('detail-'+g.id)}>详情</button><a className="softbutton small" href={`/labels/${g.id}`}>标签</a></div></div>)}{!goods.length&&<div className="empty">还没有货品。先录入第一件货。</div>}</div>
  {form.startsWith('detail-')&&<GoodDetail id={form.slice(7)} actor={me} onAction={act}/>}
  <div className="section"><h2>盘点任务</h2>{takes.map(t=><div className="item" key={t.id}><div className="body"><h3>{date(t.createdAt)} · {t.status==='OPEN'?'进行中':'已完成'}</h3><p>账面 {t.items.length} 件 · 已核对 {t.items.filter((i:any)=>i.seen).length} 件</p></div>{t.status==='OPEN'&&<button className="softbutton small" onClick={()=>open('take-'+t.id)}>核对</button>}</div>)}{form.startsWith('take-')&&<Form title="扫码或输入货号核对" onSubmit={(e:any)=>{e.preventDefault();scanStocktake(form.slice(5),f(new FormData(e.currentTarget),'code'))}}><div className="span2 scan-search"><label>货号<input name="code" required value={stocktakeCode} onChange={e=>setStocktakeCode(e.target.value)}/></label><CameraScanner onScan={setStocktakeCode}/></div></Form>}{form.startsWith('take-')&&<StocktakeReview take={takes.find(t=>t.id===form.slice(5))} goods={goods} canClose={me.role==='OWNER'||!!me.permissions?.stockApprove} onClose={reason=>act(`stocktakes/${form.slice(5)}/close`,{reason},'盘点已结束')} onResolve={resolveFinding}/> }</div></>}
  {tab==='goods'&&<DamageReview damages={damages} goods={goods} canView={me.role==='OWNER'||!!me.permissions?.stock||!!me.permissions?.returns} canReview={me.role==='OWNER'} onReview={(id,body)=>act(`damages/${id}/review`,body,'异常货复核已记录')}/>}
  {tab==='loans'&&<><div className="actions"><button className="primary" onClick={()=>open('loan')}>＋ 新建拿货单</button></div>{form==='loan'&&<Form title="客户拿货" submit={`确认交接（${selected.length}件）`} onSubmit={submit('loans',x=>({partnerId:f(x,'partnerId'),receiverName:f(x,'receiverName'),dueAt:f(x,'dueAt')||undefined,note:f(x,'note'),goodIds:selected,prices:Object.fromEntries(selected.map(id=>[id,f(x,`ref-${id}`)])),agreed:Object.fromEntries(selected.map(id=>[id,f(x,`agreed-${id}`)]))}))}><Select label="拿货客户" name="partnerId" options={partners}/><Field label="实际接收人" name="receiverName" required/><Field label="约定归还日期" name="dueAt" type="date"/><Field label="备注" name="note"/><div className="span2"><strong>选择货品</strong><div className="scan-search"><input className="search" placeholder="扫码枪输入或搜索货号、名称" value={pickerSearch} onChange={e=>setPickerSearch(e.target.value)}/><CameraScanner onScan={code=>{setPickerSearch(code);const good=goodOptions.find(g=>g.code===code);if(good)setSelected(ids=>ids.includes(good.id)?ids:[...ids,good.id]);else setError(`未找到可拿货的货品：${code}`)}}/></div><div className="chips" style={{marginTop:8}}>{goodOptions.filter(g=>!pickerSearch||`${g.code} ${g.name}`.includes(pickerSearch)).slice(0,30).map(g=><button type="button" className={`chip ${selected.includes(g.id)?'selected':''}`} key={g.id} onClick={()=>toggle(g.id)}>{g.code} {g.name}</button>)}</div></div>{selectedGoods.map(g=><div className="span2 row" key={g.id}><strong>{g.code}</strong><Field label="参考报价（元）" name={`ref-${g.id}`} defaultValue={g.askingCents||''}/><Field label="成交后应结金额（元，可空）" name={`agreed-${g.id}`}/></div>)}</Form>}
  <div className="list">{loans.map(l=><div className="card" key={l.id}><div className="row between"><strong>{l.number}</strong><span className="muted">{date(l.createdAt)}</span></div><p>{l.partner.name} · 接收人 {l.receiverName} · 应还 {date(l.dueAt)}</p><div className="chips">{l.items.map((i:any)=><button className="chip" key={i.id} onClick={()=>open('loanitem-'+i.id)}>{i.good.code} · {({OUT:'未归还',RETURNED:'已归还',SOLD:'已成交'} as any)[i.status]||i.status}{i.referencePriceCents?` · 参考 ${price(i.referencePriceCents)}`:''}{i.agreedSettlementCents?` · 应结 ${price(i.agreedSettlementCents)}`:''}</button>)}</div></div>)}{!loans.length&&<div className="empty">暂无拿货单。</div>}</div>
  {form.startsWith('loanitem-')&&(()=>{const item=loans.flatMap(l=>l.items).find((i:any)=>i.id===form.slice(9));return item?.status==='OUT'?<div className="panel"><h2>{item.good.code} · 处理外借货</h2><div className="actions"><button className="primary" onClick={()=>open('return-'+item.id)}>归还验货</button><button className="softbutton" onClick={()=>{choose('accounts');open('sale')}}>确认成交</button><button className="softbutton" onClick={()=>open('transfer-'+item.id)}>登记转交</button></div></div>:null})()}
  {form.startsWith('return-')&&<Form title="逐件归还验货" onSubmit={submit(`loan-items/${form.slice(7)}/return`,x=>({condition:f(x,'condition'),locationId:f(x,'locationId')||undefined,note:f(x,'note')}))}><Field label="验货结果"><select name="condition"><option value="NORMAL">正常</option><option value="DAMAGED">异常或货损，进入待处理</option></select></Field><Select label="存放位置" name="locationId" options={locations} required={false}/><Field label="异常说明" name="note"/></Form>}
  {form.startsWith('transfer-')&&<Form title="记录转交" onSubmit={submit(`loan-items/${form.slice(9)}/transfer`,x=>({confirmed:f(x,'confirmed')==='yes',partnerId:f(x,'partnerId')||undefined,note:f(x,'note')}))}><Field label="核实情况"><select name="confirmed"><option value="no">仅听说，待核实（原拿货人继续负责）</option><option value="yes">已核实并授权承接责任</option></select></Field><Select label="实际接收人" name="partnerId" options={partners} required={false}/><Field label="交接记录或线索" name="note" required/></Form>}</>}
  {tab==='accounts'&&<><div className="actions"><button className="primary" onClick={()=>open('sale')}>＋ 确认成交</button><button className="softbutton" onClick={()=>open('receipt')}>登记收款</button><button className="softbutton" onClick={()=>open('payment')}>付给上游</button><button className="softbutton" onClick={()=>open('opening')}>期初余额</button></div>
  {form==='sale'&&<Form title="确认成交" submit={`确认成交（${selected.length}件）`} onSubmit={submit('sales',x=>({customerId:f(x,'customerId'),discount:f(x,'discount')||'0',delivered:f(x,'delivered')==='yes',items:selected.map(id=>({goodId:id,price:f(x,`price-${id}`)}))}))}><Select label="客户" name="customerId" options={partners}/><Field label="整单优惠（元）" name="discount" defaultValue="0"/><Field label="摊位成交已交付？"><select name="delivered"><option value="no">未交付</option><option value="yes">已交付</option></select></Field><div className="span2"><strong>选货并逐件填写成交价</strong><div className="scan-search"><input className="search" placeholder="扫码枪输入或搜索货号、名称" value={pickerSearch} onChange={e=>setPickerSearch(e.target.value)}/><CameraScanner onScan={code=>{setPickerSearch(code);const good=[...goodOptions,...loanOptions].find(g=>g.code===code);if(good)setSelected(ids=>ids.includes(good.id)?ids:[...ids,good.id]);else setError(`未找到可成交的货品：${code}`)}}/></div><div className="chips" style={{marginTop:8}}>{[...goodOptions,...loanOptions].filter(g=>!pickerSearch||`${g.code} ${g.name}`.includes(pickerSearch)).slice(0,30).map(g=><button className={`chip ${selected.includes(g.id)?'selected':''}`} type="button" key={g.id} onClick={()=>toggle(g.id)}>{g.code} {g.name}</button>)}</div></div>{selectedGoods.map(g=><Field key={g.id} label={`${g.code} 成交价（元）`} name={`price-${g.id}`} defaultValue={g.askingCents||''} required/>)}</Form>}
  {form==='receipt'&&<Form title="登记实际收款" onSubmit={submit('receipts',x=>({partnerId:f(x,'partnerId'),kind:f(x,'kind'),amount:f(x,'amount'),method:f(x,'method'),note:f(x,'note')}))}><Select label="付款客户" name="partnerId" options={partners}/><Field label="款项性质"><select name="kind"><option value="SALES">销售货款（暂存，稍后核销）</option><option value="DEPOSIT">货物押金</option><option value="ADVANCE">预付款</option></select></Field><Field label="实收金额（元）" name="amount" required/><Field label="方式" name="method" defaultValue="线下转账"/><Field label="备注" name="note"/></Form>}
  {form==='payment'&&<Form title="付给上游" onSubmit={submit('payments',x=>({ownerId:f(x,'ownerId'),amount:f(x,'amount'),method:f(x,'method'),allocations:[f(x,'target').startsWith('opening:')?{openingEntryId:f(x,'target').slice(8),amount:f(x,'amount')}:{payableId:f(x,'target'),amount:f(x,'amount')}]}))}><Select label="上游货主" name="ownerId" options={partners}/><Field label="待付明细"><select name="target" required><option value="">选择</option>{payables.filter(p=>Number(p.amountCents)+Number(p.adjustedCents)>Number(p.paidCents)).map(p=><option key={p.id} value={p.id}>{p.saleItem.good.code} · {p.owner.name} · 未付{price(Number(p.amountCents)+Number(p.adjustedCents)-Number(p.paidCents))}</option>)}{entries.filter(e=>e.kind==='OPENING_AP'&&Number(e.amountCents)>Number(e.appliedCents)).map(e=><option key={e.id} value={`opening:${e.id}`}>期初应付 · {e.partner.name} · 未付{price(Number(e.amountCents)-Number(e.appliedCents))}</option>)}</select></Field><Field label="付款金额（元）" name="amount" required/><Field label="方式" name="method" defaultValue="线下转账"/></Form>}
  {form==='opening'&&<Form title="登记期初余额" onSubmit={submit('opening-balances',x=>({partnerId:f(x,'partnerId'),kind:f(x,'kind'),amount:f(x,'amount'),note:f(x,'note')}))}><Select label="合作方" name="partnerId" options={partners}/><Field label="余额方向"><select name="kind"><option value="AR">客户欠我</option><option value="AP">我欠上游</option></select></Field><Field label="金额（元）" name="amount" required/><Field label="来源说明" name="note"/></Form>}
  <div className="section"><h2>客户成交与欠款</h2><div className="list">{sales.map(s=><div className="card" key={s.id}><div className="row between"><strong>{s.number}</strong><span>{s.customer.name}</span></div><p className="muted">{date(s.createdAt)}</p>{s.items.map((i:any)=><div className="row between" key={i.id} style={{padding:'8px 0',borderTop:'1px solid #e8f0eb'}}><span>{i.good.code} · {i.good.name}　<span className="badge">{i.deliveryStatus==='DELIVERED'?'已交付':'未交付'}</span></span><strong>{price(i.netCents)} / 未收 {price(Number(i.netCents)-Number(i.returnedCents)-Number(i.paidCents))}</strong><button className="softbutton small" onClick={()=>open('saleitem-'+i.id)}>处理</button></div>)}{me.role==='OWNER'&&<div className="row"><button className="softbutton small" onClick={()=>open('fee-'+s.id)}>登记关联费用</button><span className="muted">已登记费用 {price((s.fees||[]).reduce((a:number,x:any)=>a+Number(x.amountCents),0))}</span></div>}</div>)}{!sales.length&&<div className="empty">暂无成交记录。</div>}</div></div>{form.startsWith('fee-')&&<Form title="登记销售关联费用" onSubmit={submit(`sales/${form.slice(4)}/fees`,x=>({amount:f(x,'amount'),reason:f(x,'reason')}))}><Field label="费用金额（元）" name="amount" required/><Field label="费用说明（如介绍费）" name="reason" required/></Form>}
  {form.startsWith('saleitem-')&&(()=>{const i=sales.flatMap(s=>s.items).find((x:any)=>x.id===form.slice(9));return i?<div className="panel"><h2>{i.good.code} · 处理成交货</h2><div className="actions">{i.deliveryStatus==='PENDING'&&<button className="primary" onClick={()=>act(`sale-items/${i.id}/deliver`,{},'已登记交付')}>登记交付</button>}<button className="softbutton" onClick={()=>open('sale-return-'+i.id)}>退货或改价退款</button></div></div>:null})()}
  {form.startsWith('sale-return-')&&<Form title="销售退货 / 改价退款" onSubmit={submit(`sale-items/${form.slice(12)}/return`,x=>({physical:f(x,'physical')==='yes',amount:f(x,'amount'),refund:f(x,'refund')||'0',reason:f(x,'reason'),damaged:f(x,'damaged')==='yes'}))}><Field label="实物是否退回"><select name="physical"><option value="yes">实物退回</option><option value="no">仅改价或退款，实物不退</option></select></Field><Field label="应收调整金额（元）" name="amount" required/><Field label="实际已退现金（元）" name="refund" defaultValue="0"/><Field label="验货情况"><select name="damaged"><option value="no">正常</option><option value="yes">货损待处理</option></select></Field><Field label="原因" name="reason" required/></Form>}
  <div className="section"><h2>收款与押金</h2><div className="list">{receipts.map(r=><div className="item" key={r.id}><div className="body"><h3>{r.partner.name} · {({SALES:'销售款',DEPOSIT:'押金',ADVANCE:'预付款'} as any)[r.kind]}</h3><p>{date(r.receivedAt)} · {r.method} · 已使用 {price(r.allocatedCents)}</p></div><strong>{price(r.amountCents)}</strong>{Number(r.amountCents)>Number(r.allocatedCents)&&<button className="softbutton small" onClick={()=>open('receipt-'+r.id)}>处理余额</button>}</div>)}</div></div>
  {form.startsWith('receipt-')&&(()=>{const r=receipts.find(x=>x.id===form.slice(8));return r?<div className="panel"><h2>处理 {r.partner.name} 的{r.kind==='SALES'?'待核销款':'押金/预付款'}</h2><p>可用 {price(Number(r.amountCents)-Number(r.allocatedCents))}</p><form className="form" onSubmit={submit(r.kind==='SALES'?`receipts/${r.id}/allocate`:`receipts/${r.id}/apply`,x=>r.kind==='SALES'?{allocations:[{saleItemId:f(x,'saleItemId'),amount:f(x,'amount')}]}:{saleItemId:f(x,'saleItemId'),amount:f(x,'amount')})}><Field label="销售明细"><select name="saleItemId" required><option value="">选择该客户未结货品</option>{sales.filter(s=>s.customerId===r.partnerId).flatMap(s=>s.items).filter((i:any)=>Number(i.netCents)-Number(i.returnedCents)>Number(i.paidCents)).map((i:any)=><option value={i.id} key={i.id}>{i.good.code} · 未收{price(Number(i.netCents)-Number(i.returnedCents)-Number(i.paidCents))}</option>)}</select></Field><Field label="核销或抵扣金额（元）" name="amount" required/><button className="primary">确认核销</button></form>{r.kind==='SALES'&&<form className="form" style={{marginTop:18}} onSubmit={submit(`receipts/${r.id}/allocate-opening`,x=>({entryId:f(x,'entryId'),amount:f(x,'amount')}))}><Field label="或核销期初应收"><select name="entryId" required><option value="">选择期初欠款</option>{entries.filter(e=>e.kind==='OPENING_AR'&&e.partnerId===r.partnerId&&Number(e.amountCents)>Number(e.appliedCents)).map(e=><option key={e.id} value={e.id}>未结 {price(Number(e.amountCents)-Number(e.appliedCents))}</option>)}</select></Field><Field label="核销金额（元）" name="amount" required/><button className="softbutton">核销期初</button></form>}{r.kind!=='SALES'&&<button className="softbutton" style={{marginTop:12}} onClick={()=>open('refund-'+r.id)}>退还剩余款</button>}</div>:null})()}
  {form.startsWith('refund-')&&<Form title="退还押金或预付款" onSubmit={submit(`receipts/${form.slice(7)}/refund`,x=>({amount:f(x,'amount'),reason:f(x,'reason')}))}><Field label="实退金额（元）" name="amount" required/><Field label="原因" name="reason" required/></Form>}
  <div className="section"><h2>上游应付</h2><div className="tablewrap"><table><thead><tr><th>上游货主</th><th>货号</th><th>应付</th><th>已付</th><th>未付</th><th>客户款</th></tr></thead><tbody>{payables.map(p=><tr key={p.id}><td>{p.owner.name}</td><td>{p.saleItem.good.code}</td><td>{price(Number(p.amountCents)+Number(p.adjustedCents))}</td><td>{price(p.paidCents)}</td><td>{price(Number(p.amountCents)+Number(p.adjustedCents)-Number(p.paidCents))}</td><td>{Number(p.saleItem.paidCents)>=Number(p.saleItem.netCents)-Number(p.saleItem.returnedCents)?'已收齐':'未收齐'}</td></tr>)}</tbody></table></div></div><div className="section"><h2>期初余额与待处理调整</h2><div className="list">{entries.filter(e=>['OPENING_AR','OPENING_AP','SUPPLIER_CREDIT_PENDING','CUSTOMER_REFUND_DUE'].includes(e.kind)).map(e=><div className="item" key={e.id}><div className="body"><h3>{e.partner.name} · {({OPENING_AR:'期初客户欠款',OPENING_AP:'期初上游应付',SUPPLIER_CREDIT_PENDING:'待追回或抵扣',CUSTOMER_REFUND_DUE:'待退客户款'} as any)[e.kind]}</h3><p>{date(e.createdAt)} · 剩余 {price(Number(e.amountCents)-Number(e.appliedCents))}</p></div>{['SUPPLIER_CREDIT_PENDING','CUSTOMER_REFUND_DUE'].includes(e.kind)&&Number(e.amountCents)>Number(e.appliedCents)&&<button className="softbutton small" onClick={()=>open('entry-'+e.id)}>处理</button>}</div>)}</div></div>{form.startsWith('entry-')&&(()=>{const e=entries.find(x=>x.id===form.slice(6));return e?<Form title={e.kind==='SUPPLIER_CREDIT_PENDING'?'处理上游已付退货差额':'登记客户补退款'} onSubmit={submit(`money-entries/${e.id}/${e.kind==='SUPPLIER_CREDIT_PENDING'?'settle-supplier':'settle-customer'}`,x=>({amount:f(x,'amount'),mode:f(x,'mode'),payableId:f(x,'payableId')||undefined,reason:f(x,'reason')}))}><Field label="金额（元）" name="amount" required/>{e.kind==='SUPPLIER_CREDIT_PENDING'&&<><Field label="方式"><select name="mode"><option value="RECOVERY">已收到上游退款</option><option value="OFFSET">抵后续应付</option></select></Field><Field label="抵扣的后续应付"><select name="payableId"><option value="">追回退款可不选</option>{payables.filter(p=>p.ownerId===e.partnerId&&Number(p.amountCents)+Number(p.adjustedCents)>Number(p.paidCents)).map(p=><option key={p.id} value={p.id}>{p.saleItem.good.code}</option>)}</select></Field></>}<Field label="处理原因" name="reason" required/></Form>:null})()}</>}
  {tab==='mine'&&<><div className="actions">{(me.role==='OWNER'||me.permissions?.partners)&&<button className="primary" onClick={()=>open('partner')}>＋ 合作方</button>}{me.role==='OWNER'&&<button className="softbutton" onClick={()=>open('location')}>＋ 存放位置</button>}{(me.role==='OWNER'||me.permissions?.shares)&&<button className="softbutton" onClick={()=>open('share')}>创建分享</button>}{me.role==='OWNER'&&<button className="softbutton" onClick={()=>open('user')}>＋ 员工</button>}{(me.role==='OWNER'||me.permissions?.goods)&&<a className="softbutton" href="/api/export?kind=goods">导出货品</a>}{(me.role==='OWNER'||me.permissions?.loans)&&<a className="softbutton" href="/api/export?kind=loans">导出拿货</a>}<button className="softbutton" onClick={async()=>{await api('logout','POST',{});setMe(null)}}>退出登录</button></div>
  {form==='partner'&&<Form title="新增合作方" onSubmit={submit('partners',x=>({name:f(x,'name'),phone:f(x,'phone'),roles:[...x.getAll('roles')],settlementType:f(x,'settlementType')||undefined,settlementFixed:f(x,'settlementFixed')||undefined,settlementRateBp:f(x,'settlementRateBp')||undefined,note:f(x,'note')}))}><Field label="名称" name="name" required/><Field label="电话" name="phone"/><Field label="身份（可多选）"><select name="roles" multiple size={4}><option value="CUSTOMER">客户</option><option value="OWNER">上游货主</option><option value="SUPPLIER">采购来源</option><option value="AGENT">代卖人</option></select></Field><Field label="寄售默认结算"><select name="settlementType"><option value="">未设置</option><option value="FIXED">固定价</option><option value="RATE">比例分成</option></select></Field><Field label="默认固定结算价（元）" name="settlementFixed"/><Field label="默认分成万分比" name="settlementRateBp"/><Field label="备注" name="note"/></Form>}
  {form==='location'&&<Form title="新增存放位置" onSubmit={submit('locations',x=>({name:f(x,'name')}))}><Field label="位置名称" name="name" required/></Form>}
  {form==='share'&&<Form title="创建受控分享链接" onSubmit={async (e:any)=>{e.preventDefault();const x=new FormData(e.currentTarget);try{const r=await api('shares','POST',{kind:f(x,'kind'),targetId:f(x,'targetId'),pin:f(x,'pin')||undefined,days:Number(f(x,'days')||7)});setShareUrl(r.url);setForm('');await load()}catch(err:any){setError(err.message)}}}><Field label="内容类型"><select name="kind"><option value="GOOD">单件货品</option><option value="LOAN">拿货未还清单</option><option value="CUSTOMER_STATEMENT">客户欠款对账单</option><option value="OWNER_STATEMENT">上游应付对账单</option></select></Field><Field label="选择货品或合作方"><select name="targetId" required><option value="">请选择</option><optgroup label="货品">{goods.map(g=><option key={g.id} value={g.id}>{g.code} · {g.name}</option>)}</optgroup><optgroup label="合作方">{partners.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</optgroup></select></Field><Field label="账单访问码（货品分享可留空）" name="pin"/><Field label="有效天数（1至30）" name="days" defaultValue="7"/></Form>}
  {form==='user'&&<Form title="新增员工" onSubmit={submit('users',x=>({login:f(x,'login'),name:f(x,'name'),password:f(x,'password'),permissions:{...Object.fromEntries([...x.getAll('permissions')].map(v=>[String(v),true])),customerIds:x.getAll('customerIds')}}))}><Field label="登录账号" name="login" required/><Field label="姓名" name="name" required/><Field label="初始密码（至少12位）" name="password" type="password" required/><Field label="允许操作"><select name="permissions" multiple size={8}><option value="partnersRead">查看合作方</option><option value="partners">编辑合作方</option><option value="goods">录货</option><option value="stock">盘点与位置</option><option value="loans">拿货与归还</option><option value="sales">确认成交</option><option value="receipts">登记收款</option><option value="imports">导入</option><option value="cost">查看成本</option><option value="financeRead">查看往来余额</option><option value="payments">上游付款</option><option value="shares">对外分享</option></select></Field><Field label="可访问的客户（按住 Ctrl 多选）"><select name="customerIds" multiple size={5} defaultValue={form.startsWith('perm-')?(users.find(x=>x.id===form.slice(5))?.permissions?.customerIds||[]):[]}>{partners.filter(p=>p.roles.includes('CUSTOMER')).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></Form>}
  {me.role==='OWNER'&&<div className="section"><h2>员工与权限</h2>{users.map(u=><div className="item" key={u.id}><div className="body"><h3>{u.name} · {u.login}</h3><p>{u.role==='OWNER'?'老板':u.active?'员工在用':'已停用'} · {Object.keys(u.permissions||{}).filter(k=>u.permissions[k]).join('、')}</p></div>{u.role==='STAFF'&&<div className="row"><button className="softbutton small" onClick={()=>open('perm-'+u.id)}>权限</button><button className="softbutton small" onClick={()=>act(`users/${u.id}/permissions`,{permissions:u.permissions,active:!u.active},u.active?'已停用':'已启用')}>{u.active?'停用':'启用'}</button></div>}</div>)}{form.startsWith('perm-')&&(()=>{const u=users.find(x=>x.id===form.slice(5));return u?<Form title={`设置 ${u.name} 的权限`} onSubmit={submit(`users/${u.id}/permissions`,x=>({active:u.active,permissions:{...Object.fromEntries([...x.getAll('permissions')].map(v=>[String(v),true])),customerIds:x.getAll('customerIds')}}))}><Field label="允许操作"><select name="permissions" multiple size={12} defaultValue={Object.keys(u.permissions||{}).filter(k=>u.permissions[k])}><option value="partnersRead">查看合作方</option><option value="partners">编辑合作方</option><option value="goods">录货</option><option value="stock">盘点与位置</option><option value="stockApprove">盘点复核</option><option value="loans">拿货与归还</option><option value="transfer">授权转交</option><option value="sales">确认成交</option><option value="receipts">登记收款</option><option value="payments">上游付款</option><option value="returns">销售退货</option><option value="cost">查看和填写成本</option><option value="financeRead">查看往来余额</option><option value="finance">期初及结算规则</option><option value="imports">导入</option><option value="shares">对外分享</option></select></Field><Field label="可访问的客户（按住 Ctrl 多选）"><select name="customerIds" multiple size={5} defaultValue={form.startsWith('perm-')?(users.find(x=>x.id===form.slice(5))?.permissions?.customerIds||[]):[]}>{partners.filter(p=>p.roles.includes('CUSTOMER')).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field></Form>:null})()}</div>}
  <div className="section"><h2>分享记录</h2>{shares.map(s=><div className="item" key={s.id}><div className="body"><h3>{s.kind} · {s.revokedAt?'已撤销':'有效至 '+date(s.expiresAt)}</h3><p>分享编号 {s.id.slice(0,8)}</p></div>{!s.revokedAt&&<button className="softbutton small" onClick={()=>act(`shares/${s.id}/revoke`,{},'已撤销分享')}>撤销</button>}</div>)}</div>
  <div className="section"><h2>合作方</h2><div className="list">{partners.map(p=><div className="item" key={p.id}><div className="placeholder">人</div><div className="body"><h3>{p.name}</h3><p>{p.phone||'未留电话'} · {p.roles.join('、')||'未分类'}</p></div>{(me.role==='OWNER'||me.permissions?.financeRead)&&<div className="row"><a className="softbutton small" href={`/api/export?kind=customer&partnerId=${encodeURIComponent(p.id)}`}>客户账</a><a className="softbutton small" href={`/api/export?kind=owner&partnerId=${encodeURIComponent(p.id)}`}>上游账</a>{me.role==='OWNER'&&<button className="softbutton small" onClick={()=>open('partner-rule-'+p.id)}>结算规则</button>}</div>}</div>)}</div></div>{form.startsWith('partner-rule-')&&(()=>{const p=partners.find(x=>x.id===form.slice(13));return p?<Form title={`${p.name} · 默认寄售规则（第${p.ruleVersion}版）`} onSubmit={submit(`partners/${p.id}/update`,x=>({settlementType:f(x,'settlementType'),settlementFixed:f(x,'settlementFixed'),settlementRateBp:f(x,'settlementRateBp')}))}><Field label="结算方式"><select name="settlementType" defaultValue={p.settlementType||''}><option value="">未设置</option><option value="FIXED">固定价</option><option value="RATE">比例分成</option></select></Field><Field label="固定价（元）" name="settlementFixed" defaultValue={p.settlementFixedCents||''}/><Field label="分成万分比" name="settlementRateBp" defaultValue={p.settlementRateBp||''}/></Form>:null})()}<div className="section"><h2>存放位置</h2><div className="chips">{locations.map(l=><span className="chip" key={l.id}>{l.name}</span>)}</div></div><div className="section"><h2>备份与规则</h2><div className="card">当前货权规则为试用配置：确认成交且完成交付后转给买家。正式使用前由老板确认。数据库和图片应一起备份；操作方法见项目说明。</div></div></>}
  </main><nav className="bottomnav">{nav.map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>choose(n.id)}><b>{n.icon}</b>{n.label}</button>)}</nav></div>;
}
function GoodDetail({id,actor,onAction}:any){const [g,setG]=useState<Any|null>(null),[error,setError]=useState('');useEffect(()=>{api('goods/'+id).then(setG)},[id]);if(!g)return <div className="panel">读取货品…</div>;return <div className="panel"><h2>{g.code} · {g.name}</h2><p>{g.category} · {g.ownershipKind==='CONSIGN'?'寄售':'自有'} · {g.occupancy}</p><p>报价 {price(g.askingCents)}　{g.costCents!==undefined?`成本 ${price(g.costCents)}`:''}</p><div className="row">{g.images?.map((i:any)=><img className="thumb" src={`/api/media/${i.id}`} key={i.id} alt={g.name}/>)}</div><label>补充货品照片<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const body=new FormData();body.set('file',file);body.set('goodId',id);const r=await fetch('/api/media',{method:'POST',body});const v=await r.json();if(!r.ok)setError(v.error);else setG(await api('goods/'+id))}}/></label>{error&&<p className="error">{error}</p>}<div className="actions">{g.occupancy==='FREE'&&<button className="softbutton small" onClick={()=>onAction(`goods/${id}/reserve`,{},'已预留')}>预留</button>}{g.occupancy==='RESERVED'&&<button className="softbutton small" onClick={()=>onAction(`goods/${id}/unreserve`,{},'已解除预留')}>解除预留</button>}{g.ownershipKind==='CONSIGN'&&g.occupancy==='FREE'&&<button className="softbutton small" onClick={()=>onAction(`goods/${id}/return-upstream`,{reason:'经办人确认退还上游'},'已登记退上游')}>退上游</button>}</div><h3>流转记录</h3>{g.movements?.map((m:any)=><p key={m.id}>{date(m.createdAt)} · {m.action} · {m.reason||''}</p>)}</div>}
function ImportBox({onDone}:any){
  const [result,setResult]=useState<Any|null>(null),[kind,setKind]=useState('goods'),[working,setWorking]=useState(false);
  const downloadErrors=(errors:Any[])=>{const csv='\uFEFF行号,错误\r\n'+errors.map(e=>`${e.row},"${String(e.message).replaceAll('"','""')}"`).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='导入错误.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  return <div className="panel"><h2>表格导入</h2><p>先选择 CSV 或 XLSX 文件预览；确认后导入。请保留外部编号以防重复。</p>
    <select value={kind} onChange={e=>{setKind(e.target.value);setResult(null)}}><option value="goods">货品</option><option value="partners">合作方</option><option value="opening">期初余额</option><option value="loans">未结拿货</option></select>
    <input type="file" accept=".csv,.xlsx" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setWorking(true);try{const body=new FormData();body.set('file',file);body.set('kind',kind);const r=await fetch('/api/import?preview=1',{method:'POST',body});setResult(await r.json())}catch{setResult({error:'预览失败，请重试'})}finally{setWorking(false)}}}/>
    {result?.error&&<p className="error">{result.error}</p>}
    {result?.rows&&<><p>共 {result.total||0} 行，错误 {result.errors?.length||0} 行</p>{result.errors?.map((e:any)=><p className="error" key={`${e.row}-${e.message}`}>第 {e.row} 行：{e.message}</p>)}{Boolean(result.errors?.length)&&<button className="softbutton" onClick={()=>downloadErrors(result.errors)}>下载错误表</button>}<button className="primary" disabled={working||!result.rows.length||Boolean(result.errors?.length)} onClick={async()=>{setWorking(true);try{const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,rows:result.rows})});setResult(await r.json());if(r.ok)onDone()}catch{setResult({error:'导入失败，请重试'})}finally{setWorking(false)}}}>{working?'处理中…':'确认导入'}</button></>}
    {result&&!result.rows&&result.created!==undefined&&<div className="card">导入完成：新增 {result.created} 行，重复 {result.duplicate||0} 行，失败 {result.failures?.length||0} 行。{result.failures?.map((e:any)=><p className="error" key={`${e.row}-${e.message}`}>第 {e.row} 行：{e.message}</p>)}{Boolean(result.failures?.length)&&<button className="softbutton" onClick={()=>downloadErrors(result.failures)}>下载错误表</button>}</div>}
  </div>
}



