import assert from 'node:assert/strict';
import { PrismaClient } from '@prisma/client';
const base='http://127.0.0.1:3000';
async function login(login,password){const r=await fetch(`${base}/api/v1/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login,password})});assert.equal(r.status,200,await r.text());return r.headers.get('set-cookie')?.split(';')[0]}
async function call(path,cookie,method='GET',body,extra={}){const r=await fetch(`${base}${path}`,{method,headers:{Cookie:cookie||'','Content-Type':'application/json',...extra},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}}
const boss=await login('boss','DemoBoss2026!');
const staff=await login('staff','DemoStaff2026!');
const goods=(await call('/api/v1/goods',boss)).data;
assert.ok(goods.length>=50);
const own=goods.find(g=>g.ownershipKind==='OWN'&&g.costCents);
assert.ok(own);
const staffGood=(await call(`/api/v1/goods/${own.id}`,staff)).data;
assert.equal('costCents' in staffGood,false);
assert.equal('floorCents' in staffGood,false);
const visiblePartners=(await call('/api/v1/partners',staff)).data;
assert.ok(visiblePartners.some(p=>p.name==='客户甲'));
assert.equal(visiblePartners.some(p=>p.name==='客户乙'),false);
const hiddenPartner=(await call('/api/v1/partners',boss)).data.find(p=>p.name==='客户乙');
assert.equal((await call(`/api/v1/partners/${hiddenPartner.id}`,staff)).status,404);
assert.equal((await call('/api/v1/payables',staff)).status,403);
const share=(await call('/api/v1/shares',boss,'POST',{kind:'GOOD',targetId:own.id,days:1})).data;
const token=share.url.split('/').pop();
const publicGood=(await call(`/api/share/${token}`,'','POST',{})).data;
assert.equal(publicGood.good.code,own.code);
assert.equal('costCents' in publicGood.good,false);
assert.equal('floorCents' in publicGood.good,false);
assert.equal('ownerPartnerId' in publicGood.good,false);
const staffExport=await fetch(`${base}/api/export?kind=goods`,{headers:{Cookie:staff}});
assert.equal(staffExport.status,200);
const staffCsv=await staffExport.text();
assert.equal(staffCsv.includes('采购成本'),false);
assert.equal(staffCsv.includes('底价'),false);
const imageForm=new FormData();
imageForm.set('goodId',own.id);
imageForm.set('file',new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL/nwAAAABJRU5ErkJggg==','base64')],'tiny.png',{type:'image/png'}));
const upload=await fetch(`${base}/api/media`,{method:'POST',headers:{Cookie:boss},body:imageForm});
const uploadText=await upload.text();
assert.equal(upload.status,200,uploadText);
const {id:imageId}=JSON.parse(uploadText);
assert.equal((await fetch(`${base}/api/media/${imageId}`)).status,403);
assert.equal((await fetch(`${base}/api/media/${imageId}?share=${encodeURIComponent(token)}`)).status,200);
const partner=(await call('/api/v1/partners',boss)).data[0];
const accountShare=(await call('/api/v1/shares',boss,'POST',{kind:'CUSTOMER_STATEMENT',targetId:partner.id,pin:'123456',days:1})).data;
const accountToken=accountShare.url.split('/').pop();
assert.equal((await call(`/api/share/${accountToken}`,'','POST',{pin:'bad'})).status,403);
assert.equal((await call(`/api/share/${accountToken}`,'','POST',{pin:'123456'})).status,200);
assert.equal((await call(`/api/v1/shares/${accountShare.id}/revoke`,boss,'POST',{})).status,200);
assert.equal((await call(`/api/share/${accountToken}`,'','POST',{pin:'123456'})).status,404);
assert.equal((await call(`/api/v1/shares/${share.id}/revoke`,boss,'POST',{})).status,200);
assert.equal((await fetch(`${base}/api/media/${imageId}?share=${encodeURIComponent(token)}`)).status,403);
process.loadEnvFile('.env');
const db=new PrismaClient();
try{
  const expiring=(await call('/api/v1/shares',boss,'POST',{kind:'GOOD',targetId:own.id,days:1})).data;
  await db.shareLink.update({where:{id:expiring.id},data:{expiresAt:new Date(Date.now()-1000)}});
  assert.equal((await call(`/api/share/${expiring.url.split('/').pop()}`,'','POST',{})).status,404);
}finally{await db.$disconnect()}
const key=`smoke-${Date.now()}`;
const payload={name:'接口验收货',category:'挂件',ownershipKind:'OWN'};
const one=await call('/api/v1/goods',boss,'POST',payload,{'Idempotency-Key':key});
const two=await call('/api/v1/goods',boss,'POST',payload,{'Idempotency-Key':key});
assert.equal(one.status,200);assert.equal(two.status,200);assert.equal(one.data.id,two.data.id);
const externalId=`SMOKE-${Date.now()}`;
const rows=[{externalId,name:'导入验收合作方',roles:'CUSTOMER'}];
const first=await call('/api/import',boss,'POST',{kind:'partners',rows});
const repeated=await call('/api/import',boss,'POST',{kind:'partners',rows});
assert.equal(first.data.created,1);assert.equal(repeated.data.created,0);
const goodExternal=`GOOD-${Date.now()}`;
const goodRows=[{externalId:goodExternal,name:'导入验收货',category:'挂件',ownershipKind:'OWN'}];
assert.equal((await call('/api/import',boss,'POST',{kind:'goods',rows:goodRows})).data.created,1);
assert.equal((await call('/api/import',boss,'POST',{kind:'goods',rows:goodRows})).data.created,0);
const openingRows=[{externalId:`AR-${Date.now()}`,partnerExternalId:externalId,kind:'AR',amount:'12.34'}];
assert.equal((await call('/api/import',boss,'POST',{kind:'opening',rows:openingRows})).data.created,1);
assert.equal((await call('/api/import',boss,'POST',{kind:'opening',rows:openingRows})).data.created,0);
const loanRows=[{externalId:`LOAN-ITEM-${Date.now()}`,documentExternalId:`LOAN-${Date.now()}`,customerExternalId:externalId,goodExternalId:goodExternal,receiverName:'导入验收接收人'}];
assert.equal((await call('/api/import',boss,'POST',{kind:'loans',rows:loanRows})).data.created,1);
assert.equal((await call('/api/import',boss,'POST',{kind:'loans',rows:loanRows})).data.created,0);
console.log('接口验收通过：登录、50件货、员工逐客户限制与字段/导出脱敏、越权拒绝、图片授权、分享白名单/访问码/撤销/过期、幂等创建、四类导入防重复。');
